openapi: 3.0.3
info:
  title: Blog APP - OpenAPI 3.0
  description: This is an API document for Xsolla Blog post web service
  version: 1.0.11
servers:
  - url: http://localhost:10002/api/v1
    variables: {}
    description: blogapp
tags:
  - name: blog
paths:
  /healthcheck:
    get:
      tags:
        - healthcheck
      summary: Get health of the service
      operationId: getHealthCheck
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
  /posts:
    get:
      tags:
        - blog
      summary: Get all blogs
      operationId: getAllBlogs
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfBlog'
    post:
      tags:
        - blog
      summary: Create a new blog
      operationId: addBlog
      requestBody:
        description: Create a new blog
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Blog'
            example:
              title: test title 1
              content: test content 1
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
        '400':
          description: Invalid input
  /posts/{blogId}:
    get:
      tags:
        - blog
      summary: Get blog by ID
      description: Returns a single blog
      operationId: getBlogById
      parameters:
        - name: blogId
          in: path
          description: ID of blog to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
        '400':
          description: Invalid ID supplied
        '404':
          description: Blog not found
    put:
      tags:
        - blog
      summary: Updates an existing blog
      description: ''
      operationId: updateBlogWithForm
      parameters:
        - name: blogId
          in: path
          description: ID of blog that needs to be updated
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Create a new blog
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Blog'
            example:
              title: update title
              content: update content
        required: true
      responses:
        '400':
          description: Invalid input
    delete:
      tags:
        - blog
      summary: Deletes a blog
      description: Delete a blog
      operationId: deleteBet
      parameters:
        - name: blogId
          in: path
          description: Blog id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid blog value
        '404':
          description: Not found
components:
  schemas:
    Blog:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        title:
          type: string
        content:
          type: string
        created_at:
          type: string
          format: date-time
          example: 2023-12-25T10:51:54.414918+08:00
        updated_at:
          type: string
          format: date-time
          example: 2023-12-25T10:51:54.414918+08:00
    HealthCheck:
      type: object
      properties:
        status:
          type: string
          example: UP
    ArrayOfBlog:
      type: array
      items:
        oneOf:
        - $ref: '#/components/schemas/Blog'
      example:
        - id: 1
          title: Title 1
          content: Content 1
          created_at: 2023-12-25T10:51:54.414918+08:00
          updated_at: 2023-12-25T10:51:54.414918+08:00
        - id: 2
          title: Title 2
          content: Content 2
          created_at: 2023-12-25T10:51:56.414918+08:00
          updated_at: 2023-12-25T10:51:56.414918+08:00
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  requestBodies:
    Blog:
      description: Blog object that needs to be added
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Blog'
        application/xml:
          schema:
            $ref: '#/components/schemas/Blog'
  securitySchemes:
    blogpost_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:blogs: modify blog
            read:blogs: read blog
    api_key:
      type: apiKey
      name: api_key
      in: header
